### ISSUE TITLE
Implement Inventory and Inventory Tracking

### ISSUE THREAD

**Issue by coreyjackwilson** [CS410-2015Fall/Group_25_Locl#9]
- [ ] Customer can put in current inventory when setting up the sale
- [ ] Database can track inventory
- [ ] When store makes a sale, there is a button to make a request to decrement the inventory
- [ ] When the inventory is 0, the sale is removed from the database

POSSIBLE
- [ ] Customer can be notified when inventory levels for a sale are low
